version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/blog_node_nest?schema=public"
      JWT_SECRET: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"
      MONGODB_URI: "mongodb://mongo:27017/activities"
      RABBIT_URI: "amqp://guest:guest@rabbitmq:5672"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      - db
      - mongo
      - rabbitmq
      - redis
    ports:
      - "3000:3000"  # Expose aplikasi NestJS ke localhost:3000

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_node_nest
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"      # untuk AMQP protocol
      - "15672:15672"    # untuk RabbitMQ Management UI

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  db_data:
  mongo_data:
